"""Pixel-art Mimir (God of War) for the welcome banner.

Generated by downscaling the reference portrait to an 8-row truecolor
half-block grid (▀/▄ cells, fg/bg = pixel pairs), sized to sit beside the
welcome banner like Claude Code's small logo. Regenerate, do not hand-edit.
"""

MIMIR_ART = [
    ' [#8c7553]▄[/][#705c43 on #715e44]▀[/][#44362b]▀[/]    [#705c43 on #695641]▀[/][#907855]▄[/] ',
    ' [#947655 on #674f38]▀[/][#876e4c on #846844]▀[/][#5d4741 on #56473b]▀[/][#caa399 on #dbbeb3]▀[/][#dabaae on #fadecd]▀[/][#cda89d on #e3c4b9]▀[/][#614b45 on #5a4a40]▀[/][#826a49 on #816643]▀[/][#967856 on #6c513a]▀[/] ',
    ' [#5e4742 on #997671]▀[/][#58463c on #d7b8ad]▀[/][#bba59b on #f2d7cb]▀[/][#ebcfc1 on #f2d5c8]▀[/][#e2c6b9 on #e8ccbf]▀[/][#eacfc2 on #efd3c7]▀[/][#c5aea3 on #e2c9c5]▀[/][#5c4b40 on #d3b6af]▀[/][#5e4741 on #a37f77]▀[/] ',
    '[#90716b]▄[/][#9b7871 on #aa877e]▀[/][#987a6e on #ae8c82]▀[/][#655c57]▀[/][#c8afa2 on #95766d]▀[/][#c6a094 on #caafa9]▀[/][#b49d91 on #8a6f53]▀[/][#a59064 on #e6cd5c]▀[/][#a4866b on #dfbb77]▀[/][#997672 on #9d7a77]▀[/][#96776f]▄[/]',
    '[#5b4746]▀[/][#af9288 on #745a53]▀[/][#edcabb on #dbb5a7]▀[/][#cda79a on #e4c6b6]▀[/][#e0bcae on #a7887c]▀[/][#e8ccc0 on #e0c2b5]▀[/][#dfbaad on #a6867d]▀[/][#d6b291 on #d7b8b0]▀[/][#ecc9b4 on #dcb6aa]▀[/][#b6978f on #7a5e57]▀[/][#5f4a49]▀[/]',
    '[#695e58]▄[/][#645a57 on #8b847c]▀[/][#9f7b72 on #5e504e]▀[/][#967e77 on #7b746e]▀[/][#655f5a on #6a605c]▀[/][#544242 on #4c3938]▀[/][#615854 on #685d59]▀[/][#917c73 on #7a746d]▀[/][#a37e75 on #645855]▀[/][#665b58 on #837b73]▀[/][#6a5d57]▄[/]',
    '[#62554e on #524844]▀[/][#7b726a on #6f6057]▀[/][#69625e on #70665f]▀[/][#635551 on #51413f]▀[/][#83625c on #87746c]▀[/][#6d524e on #807e76]▀[/][#84625c on #88766e]▀[/][#675854 on #52413e]▀[/][#66615c on #6e665f]▀[/][#6d625c on #7c7168]▀[/][#6d6059 on #5e5551]▀[/]',
    ' [#7b6e66 on #605553]▀[/][#5c534f on #5b4e4a]▀[/][#6e6560 on #786d64]▀[/][#89827a on #796e65]▀[/][#7e746b on #665750]▀[/][#756961 on #7a6e66]▀[/][#6c625b on #7f766d]▀[/][#615956 on #594a47]▀[/][#7c6e66 on #5b4e4a]▀[/] ',
]
